Refactor the firmware to use uclibc binaries
Faster startup
Cleaner overlay
Added GCC on the printer

diff --git a/files/1-buildroot/usr/bin/strace-log-merge b/files/1-buildroot/usr/bin/strace-log-merge
--- a/files/1-buildroot/usr/bin/strace-log-merge
+++ b/files/1-buildroot/usr/bin/strace-log-merge
@@ -3,7 +3,7 @@
 # This script processes strace -ff -tt output.  It merges the contents of all
 # STRACE_LOG.PID files and sorts them, printing result on the standard output.
 #
-# Copyright (c) 2012-2024 The strace developers.
+# Copyright (c) 2012-2021 The strace developers.
 #
 # SPDX-License-Identifier: LGPL-2.1-or-later
 
@@ -26,7 +26,7 @@ ds='\([0-9][0-9]*\)'
 if [ $# -ne 1 ]; then
 	show_usage >&2
 	exit 1
-elif [ "$1" = '--help' ] || [ "$1" = '-h' ]; then
+elif [ "$1" = '--help' ]; then
 	show_usage
 	exit 0
 fi
@@ -86,5 +86,5 @@ iterate_logfiles process_logfile |
 
 rc=$?
 [ $rc -eq 1 ] &&
-	echo >&2 "${0##*/}: $logfile.* files do not look like log files produced by 'strace -tt'"
+	echo >&2 "${0##*/}: $logfile: strace output not found"
 exit $rc
